name: OWASP ZAP Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0  # Use the correct version
        with:
          target: 'https://your-app-url.com'
          fail_action: false  # Prevents build failure on security findings
          docker_name: 'ghcr.io/zaproxy/zap2docker-stable' # Updated Docker image

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: ZAP-Report
          path: report_html.html

      - name: Authenticate with GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u zehra166 --password-stdin

      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'https://your-app-url.com'
          fail_action: false
          docker_name: 'ghcr.io/zaproxy/zap2docker-stable'


