jobs:
  zap_scan:
    runs-on: ubuntu-latest

    services:
      web:
        image: my-web-app:latest
        ports:
          - 8080:8080

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Pull and Run Web Application
        run: docker pull my-web-app:latest
